#!/usr/bin/env bash
# API CRAG-style base generation + COVER-RAG v13 plug-in.
#
# CRAG is retrieval-side correction: evaluate retrieved documents, filter or
# supplement them from the top100 pool, then generate a citation-grounded draft.
# COVER-RAG is answer-side correction: audit/repair the generated answer at
# claim level. This script runs both v0 (raw CRAG) and v3 (COVER-CRAG).
#
# Launch:
#   nohup bash scripts/run_api_crag_cover_nohup.sh \
#     > logs/api_crag_cover_v13_$(date +%Y%m%d_%H%M%S).log 2>&1 &

set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR" || exit 1

export PYTHON="${PYTHON:-/home/anaconda/envs/alce/bin/python}"
export API_CRAG_MODEL="${API_CRAG_MODEL:-gpt-4o-mini}"
export OPENAI_API_BASE="${OPENAI_API_BASE:-${OPENAI_BASE_URL:-}}"
export OPENAI_BASE_URL="${OPENAI_BASE_URL:-$OPENAI_API_BASE}"

EXPERIMENT_NAME="${EXPERIMENT_NAME:-api_crag_cover_v13}"
export BASE_DIR="${BASE_DIR:-result/${EXPERIMENT_NAME}_full}"
API_RAW_DIR="$BASE_DIR/api_crag_raw"
mkdir -p "$API_RAW_DIR" "$BASE_DIR" logs cache

ASQA_INPUT="${ASQA_INPUT:-result/origin/asqa-gpt-4o-mini-gtr-shot2-ndoc5-42.json}"
ELI5_INPUT="${ELI5_INPUT:-result/origin/eli5-gpt-4o-mini-bm25-shot2-ndoc5-42.json}"
QAMPARI_INPUT="${QAMPARI_INPUT:-result/origin/qampari-gpt-4o-mini-gtr-shot2-ndoc5-42.json}"

ASQA_DOCS="${ASQA_DOCS:-data/asqa_eval_gtr_top100_bge_reranked.json}"
ELI5_DOCS="${ELI5_DOCS:-data/eli5_eval_bm25_top100_bge_reranked.json}"
QAMPARI_DOCS="${QAMPARI_DOCS:-data/qampari_eval_gtr_top100_bge_reranked.json}"

ASQA_RAW_OUT="$API_RAW_DIR/asqa-api-crag.json"
ELI5_RAW_OUT="$API_RAW_DIR/eli5-api-crag.json"
QAMPARI_RAW_OUT="$API_RAW_DIR/qampari-api-crag.json"

API_CRAG_WORKERS="${API_CRAG_WORKERS:-2}"
API_CRAG_LIMIT="${API_CRAG_LIMIT:-}"
API_CRAG_EVALUATOR="${API_CRAG_EVALUATOR:-api}"
API_CRAG_MAX_DOC_POOL="${API_CRAG_MAX_DOC_POOL:-100}"
API_CRAG_MAX_EVAL_DOCS="${API_CRAG_MAX_EVAL_DOCS:-8}"
API_CRAG_MAX_OUTPUT_DOCS="${API_CRAG_MAX_OUTPUT_DOCS:-6}"
API_CRAG_REFINED_SENTENCES="${API_CRAG_REFINED_SENTENCES:-4}"
API_CRAG_MAX_TOKENS="${API_CRAG_MAX_TOKENS:-450}"
FORCE_API_CRAG="${FORCE_API_CRAG:-0}"

run_step() {
  local label="$1"
  shift
  echo
  echo "=== $label ==="
  echo "+ $*"
  "$@"
  local status=$?
  if [ "$status" -ne 0 ]; then
    echo "FAILED: $label exited with $status"
    exit "$status"
  fi
}

run_api_crag_one() {
  local dataset="$1"
  local input="$2"
  local docs="$3"
  local output="$4"
  if [ ! -f "$input" ]; then
    echo "WARNING: skip $dataset because input missing: $input"
    return 0
  fi
  if [ "$FORCE_API_CRAG" != "1" ] && [ -f "$output" ]; then
    echo "API CRAG output exists, skip $dataset: $output"
    return 0
  fi
  local cmd=(
    "$PYTHON" scripts/run_api_crag.py
    --input "$input"
    --output "$output"
    --dataset "$dataset"
    --model "$API_CRAG_MODEL"
    --candidate-docs-file "$docs"
    --evaluator "$API_CRAG_EVALUATOR"
    --max-doc-pool "$API_CRAG_MAX_DOC_POOL"
    --max-eval-docs "$API_CRAG_MAX_EVAL_DOCS"
    --max-output-docs "$API_CRAG_MAX_OUTPUT_DOCS"
    --refined-sentences-per-doc "$API_CRAG_REFINED_SENTENCES"
    --max-tokens "$API_CRAG_MAX_TOKENS"
    --workers "$API_CRAG_WORKERS"
    --cache-file "cache/api_crag_${dataset}_${API_CRAG_MODEL}_cache.json"
    --pretty
  )
  if [ -n "$API_CRAG_LIMIT" ]; then
    cmd+=(--limit "$API_CRAG_LIMIT")
  fi
  run_step "Generate API CRAG $dataset" "${cmd[@]}"
}

echo "=== API CRAG-style + COVER-RAG v13 ==="
echo "Base dir: $BASE_DIR"
echo "API model: $API_CRAG_MODEL"
echo "CRAG evaluator: $API_CRAG_EVALUATOR"
echo "OpenAI base: $OPENAI_API_BASE"
if [ -z "${OPENAI_API_KEY:-}" ]; then
  echo "WARNING: OPENAI_API_KEY is not set."
fi

run_api_crag_one "asqa" "$ASQA_INPUT" "$ASQA_DOCS" "$ASQA_RAW_OUT"
run_api_crag_one "eli5" "$ELI5_INPUT" "$ELI5_DOCS" "$ELI5_RAW_OUT"
run_api_crag_one "qampari" "$QAMPARI_INPUT" "$QAMPARI_DOCS" "$QAMPARI_RAW_OUT"

export ASQA_RAW="$ASQA_RAW_OUT"
export ELI5_RAW="$ELI5_RAW_OUT"
export QAMPARI_RAW="$QAMPARI_RAW_OUT"
export ASQA_DOCS="$ASQA_DOCS"
export ELI5_DOCS="$ELI5_DOCS"
export QAMPARI_DOCS="$QAMPARI_DOCS"

# CRAG is a different base method. Always rebuild v0 from the raw CRAG outputs
# unless the caller explicitly overrides these variables.
export PREPARE_V0="${CRAG_PREPARE_V0:-1}"
export V0_SUMMARY_CSV="${CRAG_V0_SUMMARY_CSV:-}"
export V0_DIR="${V0_DIR:-$BASE_DIR/cover_audit}"
export V0_CACHE_FILE="${V0_CACHE_FILE:-cache/cover_audit_api_crag_v13_cache.json}"
export V0_SCORE_MODE="${V0_SCORE_MODE:-eval}"
export FORCE_V0="${FORCE_V0:-0}"

# Frozen v13 COVER-RAG plug-in settings, matching the paper main vanilla run.
export CACHE_NAMESPACE="${CACHE_NAMESPACE:-api_crag_v13_}"
export FINAL_AUDIT="${FINAL_AUDIT:-1}"
export RENDER_MODE="${RENDER_MODE:-answer_preserving}"
export NLI_PREMISE_MODE="${NLI_PREMISE_MODE:-sentence_window}"
export NLI_TOP_SENTENCES="${NLI_TOP_SENTENCES:-4}"
export NLI_SENTENCE_WINDOW_SIZE="${NLI_SENTENCE_WINDOW_SIZE:-1}"
export PRESERVE_ANSWER_SENTENCES="${PRESERVE_ANSWER_SENTENCES:-1}"
export PRESERVE_REJECTED_CRITICAL_ANSWER_SENTENCES="${PRESERVE_REJECTED_CRITICAL_ANSWER_SENTENCES:-0}"
export CITATION_POLICY="${CITATION_POLICY:-minimal}"
export SENTENCE_CITATION_SOURCE="${SENTENCE_CITATION_SOURCE:-hybrid}"
export MAX_CITATIONS_PER_CLAIM="${MAX_CITATIONS_PER_CLAIM:-2}"
export MAX_CITATIONS_PER_SENTENCE="${MAX_CITATIONS_PER_SENTENCE:-4}"
export EXPANSION_MODE="${EXPANSION_MODE:-llm}"
export EXPANSION_MAX_TOKENS="${EXPANSION_MAX_TOKENS:-240}"
export EXPANSION_OUTPUT_MODE="${EXPANSION_OUTPUT_MODE:-span_ids}"
export EXPANSION_EVIDENCE_SENTENCES="${EXPANSION_EVIDENCE_SENTENCES:-18}"
export EXPANSION_CANDIDATE_SPANS="${EXPANSION_CANDIDATE_SPANS:-56}"
export MAX_SELECTED_SPAN_IDS="${MAX_SELECTED_SPAN_IDS:-8}"
export EXPANSION_QUERY_SOURCE="${EXPANSION_QUERY_SOURCE:-question_evidence_and_rejected}"
export EXPANSION_USE_INTERMEDIATE_ANSWER="${EXPANSION_USE_INTERMEDIATE_ANSWER:-1}"
export ANSWER_TARGETED_EXPANSION="${ANSWER_TARGETED_EXPANSION:-1}"
export RECALL_ORIENTED_COMPLETION="${RECALL_ORIENTED_COMPLETION:-1}"
export RECALL_COMPLETION_MAX_TARGETS="${RECALL_COMPLETION_MAX_TARGETS:-12}"
export RECALL_COMPLETION_REJECTED_TARGETS="${RECALL_COMPLETION_REJECTED_TARGETS:-5}"
export RECALL_COMPLETION_EVIDENCE_SENTENCES="${RECALL_COMPLETION_EVIDENCE_SENTENCES:-30}"
export RECALL_COMPLETION_SUPPORTED_CLAIMS="${RECALL_COMPLETION_SUPPORTED_CLAIMS:-20}"
export RECALL_COMPLETION_MIN_SENTENCE_OVERLAP="${RECALL_COMPLETION_MIN_SENTENCE_OVERLAP:-0.0}"
export RECALL_COMPLETION_MIN_TARGET_OVERLAP="${RECALL_COMPLETION_MIN_TARGET_OVERLAP:-0.08}"
export EXPANSION_FILTER_GENERAL_ANSWER_SPANS="${EXPANSION_FILTER_GENERAL_ANSWER_SPANS:-1}"
export EXPANSION_INCLUDE_EXTRACTIVE="${EXPANSION_INCLUDE_EXTRACTIVE:-1}"
export EXPANSION_MIN_QUESTION_OVERLAP="${EXPANSION_MIN_QUESTION_OVERLAP:-0.08}"
export ANSWER_TARGETED_EXTRACTIVE_TOP_K="${ANSWER_TARGETED_EXTRACTIVE_TOP_K:-3}"
export ANSWER_TARGETED_MIN_SENTENCE_OVERLAP="${ANSWER_TARGETED_MIN_SENTENCE_OVERLAP:-0.08}"
export EXPLANATORY_EXPANSION_REQUIRE_PHRASE_SPAN="${EXPLANATORY_EXPANSION_REQUIRE_PHRASE_SPAN:-1}"
export EXPLANATORY_TITLE_SPAN_MODE="${EXPLANATORY_TITLE_SPAN_MODE:-off}"
export MAX_EXPLANATORY_EXPANDED_CLAIMS="${MAX_EXPLANATORY_EXPANDED_CLAIMS:-1}"
export MAX_EXPLANATORY_EXPANSION_VERIFICATIONS="${MAX_EXPLANATORY_EXPANSION_VERIFICATIONS:-3}"
export MIN_EXPLANATORY_ANSWER_UNIT_SCORE="${MIN_EXPLANATORY_ANSWER_UNIT_SCORE:-0.42}"
export EXPLANATORY_PRECISION_GATE="${EXPLANATORY_PRECISION_GATE:-1}"
export EXPLANATORY_PRECISION_MIN_TARGET_RELEVANCE="${EXPLANATORY_PRECISION_MIN_TARGET_RELEVANCE:-0.58}"
export EXPLANATORY_PRECISION_MIN_QUESTION_RELEVANCE="${EXPLANATORY_PRECISION_MIN_QUESTION_RELEVANCE:-0.18}"
export EXPLANATION_INTEGRATED_REFINEMENT="${EXPLANATION_INTEGRATED_REFINEMENT:-1}"
export MAX_EXPLANATION_INTEGRATED_CLAIMS="${MAX_EXPLANATION_INTEGRATED_CLAIMS:-1}"
export MAX_EXPLANATION_LENGTH_GROWTH="${MAX_EXPLANATION_LENGTH_GROWTH:-0.10}"
export CANDIDATE_OUTPUT_SELECTION="${CANDIDATE_OUTPUT_SELECTION:-0}"
export MAX_EXPANSION_CANDIDATES="${MAX_EXPANSION_CANDIDATES:-12}"
export MAX_EXPANSION_VERIFICATIONS="${MAX_EXPANSION_VERIFICATIONS:-8}"
export MAX_EXPANDED_CLAIMS="${MAX_EXPANDED_CLAIMS:-4}"
export MIN_EXPANSION_SCORE="${MIN_EXPANSION_SCORE:-0.06}"
export STRICT_EXPANSION_ANSWER_UNIT_GATE="${STRICT_EXPANSION_ANSWER_UNIT_GATE:-1}"
export STRICT_EXPANSION_MIN_TARGET_RELEVANCE="${STRICT_EXPANSION_MIN_TARGET_RELEVANCE:-0.45}"
export ANSWER_TYPE_GATE_MODE="${ANSWER_TYPE_GATE_MODE:-soft}"
export MAX_EXPANSION_CLAIM_WORDS="${MAX_EXPANSION_CLAIM_WORDS:-22}"
export MAX_VERIFIED_CLAIMS="${MAX_VERIFIED_CLAIMS:-26}"
export MAX_FINAL_CLAIMS="${MAX_FINAL_CLAIMS:-36}"

# QAMPARI uses the same answer-set selector policy as the v13 main result.
export QAMPARI_USE_SELECT="${QAMPARI_USE_SELECT:-1}"
export QAMPARI_SELECT_JOINT_DOCS="${QAMPARI_SELECT_JOINT_DOCS:-12}"
export QAMPARI_SELECT_EXPANSION_DOCS="${QAMPARI_SELECT_EXPANSION_DOCS:-12}"
export QAMPARI_SELECT_JOINT_CANDIDATE_SPANS="${QAMPARI_SELECT_JOINT_CANDIDATE_SPANS:-140}"
export QAMPARI_SELECT_MAX_OUTPUT_ITEMS="${QAMPARI_SELECT_MAX_OUTPUT_ITEMS:-15}"
export QAMPARI_SELECT_PRESERVE_ORIGINAL_TOP_K="${QAMPARI_SELECT_PRESERVE_ORIGINAL_TOP_K:-8}"
export QAMPARI_SELECT_PRESERVED_ORIGINAL_LABEL="${QAMPARI_SELECT_PRESERVED_ORIGINAL_LABEL:-supported}"
export QAMPARI_SELECT_BACKFILL_ORIGINAL_UNTIL="${QAMPARI_SELECT_BACKFILL_ORIGINAL_UNTIL:-15}"
export QAMPARI_SELECT_BACKFILL_REQUIRES_TYPE_SAFE="${QAMPARI_SELECT_BACKFILL_REQUIRES_TYPE_SAFE:-1}"
export QAMPARI_SELECT_KEEP_UNSUPPORTED_ORIGINAL="${QAMPARI_SELECT_KEEP_UNSUPPORTED_ORIGINAL:-1}"
export QAMPARI_SELECT_RESTORE_ORIGINAL_SUBSPANS="${QAMPARI_SELECT_RESTORE_ORIGINAL_SUBSPANS:-1}"
export QAMPARI_SELECT_DROP_OBVIOUS_BAD="${QAMPARI_SELECT_DROP_OBVIOUS_BAD:-1}"
export QAMPARI_SELECT_EMPTY_OUTPUT_POLICY="${QAMPARI_SELECT_EMPTY_OUTPUT_POLICY:-empty}"
export QAMPARI_SELECT_MAX_EXPANSION_CANDIDATES="${QAMPARI_SELECT_MAX_EXPANSION_CANDIDATES:-12}"
export QAMPARI_SELECT_MAX_CITATIONS_PER_ITEM="${QAMPARI_SELECT_MAX_CITATIONS_PER_ITEM:-1}"

export CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-50}"
export CACHE_SAVE_EVERY="${CACHE_SAVE_EVERY:-50}"
export REVISION_WORKERS="${REVISION_WORKERS:-2}"
export FORCE_V3="${FORCE_V3:-0}"
export FORCE_EVAL="${FORCE_EVAL:-0}"
export FORCE_MERGE="${FORCE_MERGE:-0}"
export ALLOW_PARTIAL="${ALLOW_PARTIAL:-0}"
export LIMIT="${COVER_LIMIT:-}"

run_step "Run COVER-RAG v13 plug-in on API CRAG outputs" \
  bash scripts/run_cover_v3_three_datasets_nohup.sh

echo
echo "=== Outputs ==="
echo "API CRAG raw outputs: $API_RAW_DIR"
echo "v0 summary: $BASE_DIR/cover_audit/cover_audit_comparison.csv"
echo "v3 summary: $BASE_DIR/cover_v3/cover_v3_comparison.csv"
echo "Required metrics: $BASE_DIR/required_metrics_summary.csv"
echo "Done."
