#!/usr/bin/env bash
# Main-task-oriented COVER-RAG v3 run for ASQA, ELI5, and QAMPARI.
#
# This setting keeps the conservative sentence-window verifier and final audit,
# but changes expansion from generic supported-claim completion to answer-unit
# completion. ASQA/ELI5 get question-aware answer-span and explanation-phrase
# candidates; QAMPARI still uses the task-specific list renderer and entity
# relevance filter.
#
# Launch:
#   FORCE_V0=1 FORCE_V3=1 FORCE_EVAL=1 FORCE_MERGE=1 \
#   nohup bash scripts/run_cover_v3_main_task_boost_nohup.sh \
#     > logs/cover_v3_main_task_boost_v8_intermediate_$(date +%Y%m%d_%H%M%S).log 2>&1 &

set -uo pipefail

export BASE_DIR="${BASE_DIR:-result/cover_v3_main_task_boost_v8_intermediate_full}"

# Use one OpenAI-compatible endpoint consistently for v0 audit, v3 revision,
# QAMPARI selection, and claim-level metrics. Keep the API key in the shell
# environment rather than in this script.
export OPENAI_API_BASE="${OPENAI_API_BASE:-${OPENAI_BASE_URL:-}}"
export OPENAI_BASE_URL="${OPENAI_BASE_URL:-$OPENAI_API_BASE}"

# The NLI model is already cached on this machine. Avoid fragile HuggingFace
# metadata checks during long runs, and avoid a stale local proxy hijacking API
# traffic. Set DISABLE_PROXY=0 if you intentionally need a proxy.
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export DISABLE_PROXY="${DISABLE_PROXY:-1}"
if [[ "$DISABLE_PROXY" == "1" ]]; then
  unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy
fi

# Keep the verifier/rendering settings that preserved claim support in the
# previous correctness-boost run.
export FINAL_AUDIT="${FINAL_AUDIT:-1}"
export RENDER_MODE="${RENDER_MODE:-answer_preserving}"
export NLI_PREMISE_MODE="${NLI_PREMISE_MODE:-sentence_window}"
export NLI_TOP_SENTENCES="${NLI_TOP_SENTENCES:-4}"
export NLI_SENTENCE_WINDOW_SIZE="${NLI_SENTENCE_WINDOW_SIZE:-1}"
export PRESERVE_ANSWER_SENTENCES="${PRESERVE_ANSWER_SENTENCES:-1}"
export PRESERVE_REJECTED_CRITICAL_ANSWER_SENTENCES="${PRESERVE_REJECTED_CRITICAL_ANSWER_SENTENCES:-0}"

# Main-task boost: mine answer-bearing spans/phrases and merge deterministic
# evidence-sentence candidates with LLM candidates for paragraph tasks.
export EXPANSION_MODE="${EXPANSION_MODE:-llm}"
export ANSWER_TARGETED_EXPANSION="${ANSWER_TARGETED_EXPANSION:-1}"
export ANSWER_TARGETED_EXTRACTIVE_TOP_K="${ANSWER_TARGETED_EXTRACTIVE_TOP_K:-2}"
export ANSWER_TARGETED_MIN_SENTENCE_OVERLAP="${ANSWER_TARGETED_MIN_SENTENCE_OVERLAP:-0.18}"
export EXPANSION_FILTER_GENERAL_ANSWER_SPANS="${EXPANSION_FILTER_GENERAL_ANSWER_SPANS:-1}"
export EXPANSION_MIN_QUESTION_OVERLAP="${EXPANSION_MIN_QUESTION_OVERLAP:-0.12}"
export EXPANSION_QUERY_SOURCE="${EXPANSION_QUERY_SOURCE:-question_evidence_and_rejected}"
export EXPANSION_USE_INTERMEDIATE_ANSWER="${EXPANSION_USE_INTERMEDIATE_ANSWER:-1}"
export EXPANSION_EVIDENCE_SENTENCES="${EXPANSION_EVIDENCE_SENTENCES:-10}"
export EXPANSION_CANDIDATE_SPANS="${EXPANSION_CANDIDATE_SPANS:-24}"
export MAX_EXPANSION_CANDIDATES="${MAX_EXPANSION_CANDIDATES:-10}"
export MAX_EXPANSION_VERIFICATIONS="${MAX_EXPANSION_VERIFICATIONS:-6}"
export MAX_EXPANDED_CLAIMS="${MAX_EXPANDED_CLAIMS:-3}"
export MIN_EXPANSION_SCORE="${MIN_EXPANSION_SCORE:-0.10}"

# Keep precision pressure: only a little extra room, and fewer citations per
# rendered sentence than the previous run.
export MAX_VERIFIED_CLAIMS="${MAX_VERIFIED_CLAIMS:-22}"
export MAX_FINAL_CLAIMS="${MAX_FINAL_CLAIMS:-28}"
export CITATION_POLICY="${CITATION_POLICY:-minimal}"
export SENTENCE_CITATION_SOURCE="${SENTENCE_CITATION_SOURCE:-source}"
export MAX_CITATIONS_PER_CLAIM="${MAX_CITATIONS_PER_CLAIM:-2}"
export MAX_CITATIONS_PER_SENTENCE="${MAX_CITATIONS_PER_SENTENCE:-2}"
export MAX_DOC_POOL="${MAX_DOC_POOL:-100}"

# Dataset-specific next-round settings. v2 showed that ASQA benefits from the
# tighter expansion gate, while ELI5 needs more explanatory candidates and a
# little more rendering room. QAMPARI is list-recall dominated, so keep it less
# aggressively capped and evaluate it as a separate trade-off.
export ASQA_ANSWER_TARGETED_EXTRACTIVE_TOP_K="${ASQA_ANSWER_TARGETED_EXTRACTIVE_TOP_K:-2}"
export ASQA_ANSWER_TARGETED_MIN_SENTENCE_OVERLAP="${ASQA_ANSWER_TARGETED_MIN_SENTENCE_OVERLAP:-0.18}"
export ASQA_EXPANSION_MIN_QUESTION_OVERLAP="${ASQA_EXPANSION_MIN_QUESTION_OVERLAP:-0.12}"
export ASQA_EXPANSION_EVIDENCE_SENTENCES="${ASQA_EXPANSION_EVIDENCE_SENTENCES:-10}"
export ASQA_EXPANSION_CANDIDATE_SPANS="${ASQA_EXPANSION_CANDIDATE_SPANS:-24}"
export ASQA_MAX_EXPANSION_CANDIDATES="${ASQA_MAX_EXPANSION_CANDIDATES:-10}"
export ASQA_MAX_EXPANSION_VERIFICATIONS="${ASQA_MAX_EXPANSION_VERIFICATIONS:-6}"
export ASQA_MAX_EXPANDED_CLAIMS="${ASQA_MAX_EXPANDED_CLAIMS:-3}"
export ASQA_MIN_EXPANSION_SCORE="${ASQA_MIN_EXPANSION_SCORE:-0.10}"
export ASQA_MAX_FINAL_CLAIMS="${ASQA_MAX_FINAL_CLAIMS:-30}"
export ASQA_MAX_CITATIONS_PER_SENTENCE="${ASQA_MAX_CITATIONS_PER_SENTENCE:-2}"

export ELI5_EXPANSION_INCLUDE_EXTRACTIVE="${ELI5_EXPANSION_INCLUDE_EXTRACTIVE:-0}"
export ELI5_EXPLANATORY_EXPANSION_REQUIRE_PHRASE_SPAN="${ELI5_EXPLANATORY_EXPANSION_REQUIRE_PHRASE_SPAN:-1}"
export ELI5_ANSWER_TARGETED_EXTRACTIVE_TOP_K="${ELI5_ANSWER_TARGETED_EXTRACTIVE_TOP_K:-6}"
export ELI5_ANSWER_TARGETED_MIN_SENTENCE_OVERLAP="${ELI5_ANSWER_TARGETED_MIN_SENTENCE_OVERLAP:-0.0}"
export ELI5_EXPANSION_MIN_QUESTION_OVERLAP="${ELI5_EXPANSION_MIN_QUESTION_OVERLAP:-0.08}"
export ELI5_EXPANSION_EVIDENCE_SENTENCES="${ELI5_EXPANSION_EVIDENCE_SENTENCES:-10}"
export ELI5_EXPANSION_CANDIDATE_SPANS="${ELI5_EXPANSION_CANDIDATE_SPANS:-24}"
export ELI5_MAX_EXPANSION_CANDIDATES="${ELI5_MAX_EXPANSION_CANDIDATES:-8}"
export ELI5_MAX_EXPANSION_VERIFICATIONS="${ELI5_MAX_EXPANSION_VERIFICATIONS:-6}"
export ELI5_MAX_EXPANDED_CLAIMS="${ELI5_MAX_EXPANDED_CLAIMS:-3}"
export ELI5_MIN_EXPANSION_SCORE="${ELI5_MIN_EXPANSION_SCORE:-0.10}"
export ELI5_MAX_FINAL_CLAIMS="${ELI5_MAX_FINAL_CLAIMS:-32}"
export ELI5_MAX_CITATIONS_PER_SENTENCE="${ELI5_MAX_CITATIONS_PER_SENTENCE:-2}"

export QAMPARI_USE_SELECT="${QAMPARI_USE_SELECT:-1}"
export QAMPARI_SELECT_JOINT_DOCS="${QAMPARI_SELECT_JOINT_DOCS:-10}"
export QAMPARI_SELECT_JOINT_CANDIDATE_SPANS="${QAMPARI_SELECT_JOINT_CANDIDATE_SPANS:-120}"
export QAMPARI_SELECT_JOINT_REQUIRE_TYPE_MATCH="${QAMPARI_SELECT_JOINT_REQUIRE_TYPE_MATCH:-1}"
export QAMPARI_SELECT_STRICT_QUESTION_TYPE_GUARD="${QAMPARI_SELECT_STRICT_QUESTION_TYPE_GUARD:-0}"
export QAMPARI_SELECT_EXPAND_FROM_DOCS="${QAMPARI_SELECT_EXPAND_FROM_DOCS:-llm}"
export QAMPARI_SELECT_MAX_OUTPUT_ITEMS="${QAMPARI_SELECT_MAX_OUTPUT_ITEMS:-10}"
export QAMPARI_SELECT_BACKFILL_ORIGINAL_UNTIL="${QAMPARI_SELECT_BACKFILL_ORIGINAL_UNTIL:-6}"
export QAMPARI_SELECT_BACKFILL_REQUIRES_TYPE_SAFE="${QAMPARI_SELECT_BACKFILL_REQUIRES_TYPE_SAFE:-1}"
export QAMPARI_SELECT_EMPTY_OUTPUT_POLICY="${QAMPARI_SELECT_EMPTY_OUTPUT_POLICY:-empty}"
export QAMPARI_SELECT_KEEP_UNSUPPORTED_ORIGINAL="${QAMPARI_SELECT_KEEP_UNSUPPORTED_ORIGINAL:-0}"
export QAMPARI_SELECT_DROP_OBVIOUS_BAD="${QAMPARI_SELECT_DROP_OBVIOUS_BAD:-1}"
export QAMPARI_SELECT_MAX_EXPANSION_CANDIDATES="${QAMPARI_SELECT_MAX_EXPANSION_CANDIDATES:-8}"
export QAMPARI_SELECT_EXPANSION_DOCS="${QAMPARI_SELECT_EXPANSION_DOCS:-8}"
export QAMPARI_SELECT_REPAIR_TOP_K="${QAMPARI_SELECT_REPAIR_TOP_K:-5}"
export QAMPARI_SELECT_MAX_CITATIONS_PER_ITEM="${QAMPARI_SELECT_MAX_CITATIONS_PER_ITEM:-1}"
export QAMPARI_ANSWER_TARGETED_EXPANSION="${QAMPARI_ANSWER_TARGETED_EXPANSION:-0}"
export QAMPARI_EXPANSION_MIN_QUESTION_OVERLAP="${QAMPARI_EXPANSION_MIN_QUESTION_OVERLAP:-0.0}"
export QAMPARI_EXPANSION_EVIDENCE_SENTENCES="${QAMPARI_EXPANSION_EVIDENCE_SENTENCES:-16}"
export QAMPARI_EXPANSION_CANDIDATE_SPANS="${QAMPARI_EXPANSION_CANDIDATE_SPANS:-40}"
export QAMPARI_MAX_EXPANSION_CANDIDATES="${QAMPARI_MAX_EXPANSION_CANDIDATES:-12}"
export QAMPARI_MAX_EXPANSION_VERIFICATIONS="${QAMPARI_MAX_EXPANSION_VERIFICATIONS:-6}"
export QAMPARI_MAX_EXPANDED_CLAIMS="${QAMPARI_MAX_EXPANDED_CLAIMS:-4}"
export QAMPARI_MIN_EXPANSION_SCORE="${QAMPARI_MIN_EXPANSION_SCORE:-0.06}"
export QAMPARI_MAX_FINAL_CLAIMS="${QAMPARI_MAX_FINAL_CLAIMS:-80}"
export QAMPARI_MAX_CITATIONS_PER_SENTENCE="${QAMPARI_MAX_CITATIONS_PER_SENTENCE:-3}"

# Resume-friendly defaults.
export CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-50}"
export CACHE_SAVE_EVERY="${CACHE_SAVE_EVERY:-50}"
export REVISION_WORKERS="${REVISION_WORKERS:-4}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash "$SCRIPT_DIR/run_cover_v3_three_datasets_nohup.sh"
