#!/usr/bin/env bash
# COVER-RAG dynamic missing-facet retrieval experiment.
#
# This run tests the retrieval-side version of recall completion:
#   supported claims + original question + rejected/missing facets
#   -> dynamically retrieve extra candidate docs from the global candidate-doc pool
#   -> expansion candidates
#   -> NLI verification
#   -> citation-safe rendering.
#
# Launch:
#   nohup bash scripts/run_cover_v3_dynamic_retrieval_nohup.sh \
#     > logs/cover_v3_dynamic_retrieval_$(date +%Y%m%d_%H%M%S).log 2>&1 &

set -uo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR" || exit 1

export EXPERIMENT_NAME="${EXPERIMENT_NAME:-cover_v3_dynamic_retrieval_v3_coverage_guided_fast}"
export CACHE_NAMESPACE="${CACHE_NAMESPACE:-dynamic_retrieval_v3_fast_}"
export USE_EXTERNAL_CACHE_NAMESPACE="${USE_EXTERNAL_CACHE_NAMESPACE:-1}"
export PREPARE_V0="${PREPARE_V0:-0}"

# Keep the previous stable recall-completion stack, but allow each item to
# retrieve evidence outside its own top100 candidate pool.
export DYNAMIC_RETRIEVAL_MODE="${DYNAMIC_RETRIEVAL_MODE:-global_candidate_docs}"
export DYNAMIC_RETRIEVAL_TOP_K="${DYNAMIC_RETRIEVAL_TOP_K:-4}"
export DYNAMIC_RETRIEVAL_PER_QUERY_DOCS="${DYNAMIC_RETRIEVAL_PER_QUERY_DOCS:-2}"
export DYNAMIC_RETRIEVAL_MAX_QUERIES="${DYNAMIC_RETRIEVAL_MAX_QUERIES:-2}"
export DYNAMIC_RETRIEVAL_MAX_REJECTED_CLAIMS="${DYNAMIC_RETRIEVAL_MAX_REJECTED_CLAIMS:-4}"
export DYNAMIC_RETRIEVAL_MAX_DOC_POOL="${DYNAMIC_RETRIEVAL_MAX_DOC_POOL:-108}"
export DYNAMIC_RETRIEVAL_QUERY_MAX_CHARS="${DYNAMIC_RETRIEVAL_QUERY_MAX_CHARS:-900}"
export DYNAMIC_RETRIEVAL_MIN_QUERY_TERMS="${DYNAMIC_RETRIEVAL_MIN_QUERY_TERMS:-2}"
export DYNAMIC_RETRIEVAL_SENTENCE_BOOST="${DYNAMIC_RETRIEVAL_SENTENCE_BOOST:-0.12}"
export DYNAMIC_RETRIEVAL_QUERY_STRATEGY="${DYNAMIC_RETRIEVAL_QUERY_STRATEGY:-missing_facet}"
export DYNAMIC_RETRIEVAL_MIN_SCORE="${DYNAMIC_RETRIEVAL_MIN_SCORE:-0.08}"
export DYNAMIC_RETRIEVAL_REQUIRE_MISSING_SIGNAL="${DYNAMIC_RETRIEVAL_REQUIRE_MISSING_SIGNAL:-1}"
export DYNAMIC_RETRIEVAL_USE_SUPPORTED_ANSWER="${DYNAMIC_RETRIEVAL_USE_SUPPORTED_ANSWER:-1}"
export COVERAGE_GUIDED_RETRIEVAL="${COVERAGE_GUIDED_RETRIEVAL:-1}"
export COVERAGE_GUIDED_TARGETS_PER_ROUND="${COVERAGE_GUIDED_TARGETS_PER_ROUND:-2}"
export COVERAGE_GUIDED_MIN_TARGETS="${COVERAGE_GUIDED_MIN_TARGETS:-1}"
export COVERAGE_GUIDED_MIN_QUESTION_OVERLAP="${COVERAGE_GUIDED_MIN_QUESTION_OVERLAP:-0.08}"
export COVERAGE_GUIDED_QUERY_SUPPORTED_CLAIMS="${COVERAGE_GUIDED_QUERY_SUPPORTED_CLAIMS:-6}"
export COVERAGE_GUIDED_ALLOW_EVIDENCE_TARGETS="${COVERAGE_GUIDED_ALLOW_EVIDENCE_TARGETS:-1}"
export COVERAGE_RERANKER_MODEL="${COVERAGE_RERANKER_MODEL:-}"
export COVERAGE_RERANKER_DEVICE="${COVERAGE_RERANKER_DEVICE:-}"
export COVERAGE_RERANKER_BATCH_SIZE="${COVERAGE_RERANKER_BATCH_SIZE:-16}"
export COVERAGE_RERANKER_MAX_LENGTH="${COVERAGE_RERANKER_MAX_LENGTH:-384}"
export COVERAGE_RERANKER_DOC_PREFILTER="${COVERAGE_RERANKER_DOC_PREFILTER:-64}"
export COVERAGE_RERANKER_DOC_WEIGHT="${COVERAGE_RERANKER_DOC_WEIGHT:-0.35}"
export COVERAGE_RERANKER_CANDIDATE_WEIGHT="${COVERAGE_RERANKER_CANDIDATE_WEIGHT:-0.20}"

# Multi-round completion is where dynamic retrieval matters: each round sees the
# newly supported answer core and can search a narrower missing facet.
export ITERATIVE_COMPLETION_ROUNDS="${ITERATIVE_COMPLETION_ROUNDS:-1}"
export ITERATIVE_COMPLETION_MAX_NEW_CLAIMS_PER_ROUND="${ITERATIVE_COMPLETION_MAX_NEW_CLAIMS_PER_ROUND:-2}"
export ITERATIVE_COMPLETION_MAX_VERIFICATIONS_PER_ROUND="${ITERATIVE_COMPLETION_MAX_VERIFICATIONS_PER_ROUND:-3}"
export ITERATIVE_COMPLETION_EVIDENCE_SENTENCES="${ITERATIVE_COMPLETION_EVIDENCE_SENTENCES:-24}"
export ITERATIVE_COMPLETION_CANDIDATE_SPANS="${ITERATIVE_COMPLETION_CANDIDATE_SPANS:-48}"
export ITERATIVE_COMPLETION_MAX_CANDIDATES="${ITERATIVE_COMPLETION_MAX_CANDIDATES:-8}"

export EXPANSION_EVIDENCE_SENTENCES="${EXPANSION_EVIDENCE_SENTENCES:-14}"
export EXPANSION_CANDIDATE_SPANS="${EXPANSION_CANDIDATE_SPANS:-42}"
export MAX_EXPANSION_CANDIDATES="${MAX_EXPANSION_CANDIDATES:-8}"
export MAX_EXPANSION_VERIFICATIONS="${MAX_EXPANSION_VERIFICATIONS:-5}"
export MAX_EXPANDED_CLAIMS="${MAX_EXPANDED_CLAIMS:-3}"

export MAX_DOC_POOL="${MAX_DOC_POOL:-100}"
export MAX_VERIFIED_CLAIMS="${MAX_VERIFIED_CLAIMS:-28}"
export MAX_FINAL_CLAIMS="${MAX_FINAL_CLAIMS:-38}"
export CANDIDATE_OUTPUT_MIN_ANSWER_UNIT_GAIN="${CANDIDATE_OUTPUT_MIN_ANSWER_UNIT_GAIN:-0.55}"
export CANDIDATE_OUTPUT_MIN_SUPPORTED_CLAIM_GAIN="${CANDIDATE_OUTPUT_MIN_SUPPORTED_CLAIM_GAIN:-1}"
export CANDIDATE_OUTPUT_SUPPORT_TOLERANCE="${CANDIDATE_OUTPUT_SUPPORT_TOLERANCE:-0.005}"
export CANDIDATE_OUTPUT_MAX_UNSUPPORTED_RATE="${CANDIDATE_OUTPUT_MAX_UNSUPPORTED_RATE:-0.045}"
export REVISION_WORKERS="${REVISION_WORKERS:-4}"
export CACHE_SAVE_EVERY="${CACHE_SAVE_EVERY:-200}"

echo "=== COVER-RAG dynamic missing-facet retrieval launcher ==="
echo "Experiment: $EXPERIMENT_NAME"
echo "Dynamic retrieval: mode=$DYNAMIC_RETRIEVAL_MODE strategy=$DYNAMIC_RETRIEVAL_QUERY_STRATEGY coverage_guided=$COVERAGE_GUIDED_RETRIEVAL top_k=$DYNAMIC_RETRIEVAL_TOP_K per_query=$DYNAMIC_RETRIEVAL_PER_QUERY_DOCS min_score=$DYNAMIC_RETRIEVAL_MIN_SCORE max_doc_pool=$DYNAMIC_RETRIEVAL_MAX_DOC_POOL"
echo "Coverage controller: targets_per_round=$COVERAGE_GUIDED_TARGETS_PER_ROUND min_targets=$COVERAGE_GUIDED_MIN_TARGETS min_q_overlap=$COVERAGE_GUIDED_MIN_QUESTION_OVERLAP allow_evidence_targets=$COVERAGE_GUIDED_ALLOW_EVIDENCE_TARGETS"
echo "Coverage-aware reranker: ${COVERAGE_RERANKER_MODEL:-off} device=${COVERAGE_RERANKER_DEVICE:-auto} batch=$COVERAGE_RERANKER_BATCH_SIZE doc_weight=$COVERAGE_RERANKER_DOC_WEIGHT candidate_weight=$COVERAGE_RERANKER_CANDIDATE_WEIGHT"
echo "Iterative completion: rounds=$ITERATIVE_COMPLETION_ROUNDS new_per_round=$ITERATIVE_COMPLETION_MAX_NEW_CLAIMS_PER_ROUND"
echo "Candidate guard: min_unit_gain=$CANDIDATE_OUTPUT_MIN_ANSWER_UNIT_GAIN min_supported_gain=$CANDIDATE_OUTPUT_MIN_SUPPORTED_CLAIM_GAIN support_tol=$CANDIDATE_OUTPUT_SUPPORT_TOLERANCE max_unsupported=$CANDIDATE_OUTPUT_MAX_UNSUPPORTED_RATE"
echo "Revision workers: $REVISION_WORKERS"

bash scripts/run_cover_v3_recall_repair_nohup.sh
